# Generated by Django 5.2.3 on 2025-07-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
