# Generated by Django 5.2.3 on 2025-06-22 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('lagradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=7, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=25)),
                ('pais', models.CharField(default='BRASIL', max_length=50)),
                ('apelido', models.CharField(default='CASA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('aniversario', models.DateField(blank=True, default=None, null=True)),
                ('enderecos', models.ManyToManyField(blank=True, default=None, null=True, related_name='lista_de_enderecos', to='contas.endereco')),
            ],
        ),
    ]
