# Generated by Django 5.2.3 on 2025-07-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_endereco_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(blank=True, default=None, related_name='lista_de_enderecos', to='contas.endereco'),
        ),
    ]
