# Generated by Django 5.2.3 on 2025-07-27 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminSite', '0002_alter_produto_custo_alter_produto_preco'),
        ('contas', '0003_alter_cliente_enderecos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_criados', to='adminSite.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('itens_total', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.cliente')),
                ('itens', models.ManyToManyField(blank=True, default=None, null=True, related_name='itens_carrinho', to='comprar.item')),
            ],
        ),
    ]
