# Generated by Django 5.2.3 on 2025-08-05 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSite', '0002_alter_produto_custo_alter_produto_preco'),
        ('comprar', '0001_initial'),
        ('contas', '0003_alter_cliente_enderecos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos', models.ManyToManyField(blank=True, default=None, null=True, related_name='produtos_favoritos', to='adminSite.produto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contas.cliente')),
            ],
        ),
    ]
